apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-stalwart-recovery-admin
  namespace: stalwart
spec:
  vaultAuthRef: vault-k8s
  mount: k3s-infra
  type: kv-v2
  path: stalwart/recovery-admin
  refreshAfter: 1h
  destination:
    create: true
    name: stalwart-recovery-admin
    labels:
      app.kubernetes.io/part-of: stalwart
