---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  vaultAuthRef: vault-secrets/vault-k8s
  type: kv-v2
  mount: k3s-infra
  path: tailscale-operator
  refreshAfter: 1h
  destination:
    create: true
    name: operator-oauth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-auth
  namespace: tailscale
