# In-cluster DNS override for the Vault hostname.
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  vault.server: |
    vault.int.felixwallner.com:53 {
      hosts {
        192.168.178.254 vault.int.felixwallner.com
        fallthrough
      }
      forward . /etc/resolv.conf
    }
