# ntfy access token for Grafana's webhook contact point.
# keys: `token`
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-grafana-ntfy
  namespace: grafana
spec:
  vaultAuthRef: vault-k8s
  mount: k3s-infra
  type: kv-v2
  path: grafana/ntfy
  refreshAfter: 1h
  destination:
    create: true
    name: grafana-ntfy
    labels:
      app.kubernetes.io/part-of: grafana
