# ntfy access token for Alertmanager, mounted at
# /etc/alertmanager/secrets/alertmanager-ntfy/token
# keys: `token`
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-alertmanager-ntfy
  namespace: monitoring
spec:
  vaultAuthRef: vault-k8s
  mount: k3s-infra
  type: kv-v2
  path: monitoring/ntfy
  refreshAfter: 1h
  destination:
    create: true
    name: alertmanager-ntfy
