apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: infra-apps-project
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 10.8.4
      helm:
        releaseName: argocd
        values: |
          fullnameOverride: argocd

          global:
            securityContext:
              runAsNonRoot: true
              runAsUser: 999
              fsGroup: 999
              seccompProfile:
                type: RuntimeDefault

          configs:
            params:
              server.insecure: true
            cm:
              url: https://argocd.int.felixwallner.com
              # Re-enable it temporarily if SSO is not available.
              admin.enabled: false
              oidc.config: |
                name: authentik
                issuer: https://sso.int.felixwallner.com/application/o/argocd/
                clientID: $argocd-oidc:clientID
                clientSecret: $argocd-oidc:clientSecret
                requestedScopes:
                  - openid
                  - profile
                  - email
                  - groups
                logoutURL: https://sso.int.felixwallner.com/application/o/argocd/end-session/
            rbac:
              policy.default: ""
              scopes: "[groups]"
              policy.csv: |
                g, admins, role:admin
                g, viewers, role:readonly

    - repoURL: https://github.com/Falo04/homelab.git
      targetRevision: main
      path: apps/infra/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
