apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: infra-apps-project
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 10.1.2
      helm:
        releaseName: argocd
        values: |
          fullnameOverride: argocd

          global:
            securityContext:
              runAsNonRoot: true
              runAsUser: 999
              fsGroup: 999
              seccompProfile:
                type: RuntimeDefault

          configs:
            params:
              server.insecure: true
            cm:
              url: https://argocd.int.felixwallner.com

    - repoURL: https://github.com/Falo04/homelab.git
      targetRevision: main
      path: apps/infra/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
