apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infra-apps-project
  sources:
    - repoURL: oci://quay.io/jetstack/charts/cert-manager
      chart: cert-manager
      targetRevision: v1.20.3
      helm:
        releaseName: cert-manager
        values: |
          prometheus: 
            enabled: true
          crds:
            enabled: true

    - repoURL: https://github.com/Falo04/homelab.git
      targetRevision: main
      path: apps/infra/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
