apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fronius-exporter
  namespace: argocd
spec:
  project: infra-apps-project
  source:
    repoURL: https://github.com/Falo04/homelab.git
    targetRevision: main
    path: apps/infra/solar
  destination:
    server: https://kubernetes.default.svc
    namespace: solar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
