apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd.yaml
  - authentik.yaml
  - cert-manager.yaml
  - cloudnativepg.yaml
  - grafana.yaml
  - kube-prometheus-stack.yaml
  - ntfy.yaml
  - traefik.yaml
  - vault-secrets-operator.yaml
  - vault-secrets.yaml
