# key: `PIHOLE_ADMIN`
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-pihole-auth
  namespace: pihole
spec:
  vaultAuthRef: vault-k8s
  mount: k3s-services
  type: kv-v2
  path: pihole/auth
  refreshAfter: 1h
  rolloutRestartTargets:
    - kind: Deployment
      name: pihole
  destination:
    create: true
    name: pihole-auth
    labels:
      app.kubernetes.io/part-of: pihole
