apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wallos

resources:
  - namespace.yaml
  - vault-auth.yaml
  - oidc-secret.yaml
  - pvc-backup-values.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - wallos-cert.yaml

components:
  - ../../../base/pvc-backup
