# Values for the ../../../base/pvc-backup component.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pvc-backup-values
data:
  claimName: wallos-data
  repository: s3:https://s3.nas.felixwallner.com/wallos-bucket/restic
  vaultMount: k3s-services
  vaultPath: wallos/backup
  sqliteDatabases: "db/wallos.db"
