apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookorbit

resources:
  - namespace.yaml
  - vault-auth.yaml
  - app-secret.yaml
  - backup-values.yaml
  - pvc-backup-values.yaml
  - postgres.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - bookorbit-cert.yaml

components:
  - ../../../base/cnpg-backup
  - ../../../base/pvc-backup
