apiVersion: v1
kind: Service
metadata:
  name: bookorbit
  namespace: bookorbit
spec:
  selector:
    app.kubernetes.io/name: bookorbit
  ports:
    - name: http
      port: 80
      targetPort: http
