# Ingress policy for the Traefik pods.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: traefik
  namespace: traefik
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
  ingress:
    # Public HTTP/HTTPS entrypoints, reachable from anywhere
    - fromEntities:
        - cluster
        - world
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP

    # Prometheus metrics
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "9100"
              protocol: TCP

    # Tailscale entrypoint
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: traefik-tailscale
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
  egress:
    - toEntities:
        - all
