# Garage access key for tempo-bucket.
# keys: `ACCESS_KEY_ID` / `ACCESS_SECRET_KEY`
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-tempo-s3
  namespace: tempo
spec:
  vaultAuthRef: vault-k8s
  mount: k3s-infra
  type: kv-v2
  path: tempo/s3
  refreshAfter: 1h
  rolloutRestartTargets:
    - kind: StatefulSet
      name: tempo
  destination:
    create: true
    name: tempo-s3
    labels:
      app.kubernetes.io/part-of: tempo
