# Credentials for the authentik OAuth2 provider.
# keys: `clientID` / `clientSecret`
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-argocd-oidc
  namespace: argocd
spec:
  vaultAuthRef: vault-k8s
  mount: k3s-infra
  type: kv-v2
  path: argocd/oidc
  refreshAfter: 1h
  destination:
    create: true
    name: argocd-oidc
    labels:
      app.kubernetes.io/part-of: argocd
