apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: service-apps-project
  sources:
    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      targetRevision: 2.38.0
      helm:
        releaseName: pihole
        values: |
          DNS1: 9.9.9.9
          DNS2: 1.1.1.1 

          persistentVolumeClaim:
            enabled: true

          admin: 
            existingSecret: "pihole-auth"
            passwordKey: "PIHOLE_ADMIN"

          serviceDns:
            mixedService: true
            type: LoadBalancer
            loadBalancerIP: 192.168.178.213

          serviceDhcp:
            enabled: false

          podDnsConfig:
            enabled: false

    - repoURL: https://github.com/Falo04/homelab.git
      targetRevision: main
      path: apps/services/pihole

    - repoURL: https://github.com/Falo04/homelab.git
      targetRevision: main
      path: charts/tailscale-node
      helm:
        releaseName: pihole-tailscale
        valuesObject:
          pod:
            fullnameOverride: tailscale
          tailscale:
            hostname: pihole
            tcpForward:
              - port: 80
                targetPort: 80
                service: pihole-ingress
          vault:
            authRef: vault-k8s
            mount: k3s-services
            path: pihole/tailscale

    - repoURL: https://github.com/Falo04/homelab.git
      targetRevision: main
      path: charts/service-ingress
      helm:
        releaseName: pihole-ingress
        valuesObject:
          pod:
            fullnameOverride: pihole-ingress
          host: pihole.int.felixwallner.com
          tlsSecret: pihole-tls
          backend:
            service: pihole-web
            port: 80

  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
