# Garage access key for loki-bucket.
# keys: `ACCESS_KEY_ID` / `ACCESS_SECRET_KEY`
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-loki-s3
  namespace: loki
spec:
  vaultAuthRef: vault-k8s
  mount: k3s-infra
  type: kv-v2
  path: loki/s3
  refreshAfter: 1h
  rolloutRestartTargets:
    - kind: StatefulSet
      name: loki
  destination:
    create: true
    name: loki-s3
    labels:
      app.kubernetes.io/part-of: loki
