apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-apps-project
  namespace: argocd
spec:
  description: "All infra apps"
  sourceRepos:
    - https://github.com/Falo04/homelab.git
    - https://argoproj.github.io/argo-helm
    - https://helm.releases.hashicorp.com
    - https://traefik.github.io/charts
    - oci://quay.io/jetstack/charts/cert-manager
    - ghcr.io/tailscale/tailscale
    - https://helm.cilium.io/
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: cert-manager
    - server: https://kubernetes.default.svc
      namespace: traefik
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: vault-secrets
    - server: https://kubernetes.default.svc
      namespace: vault-secrets-operator
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
