apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-apps-project
  namespace: argocd
spec:
  description: "All infra apps"
  sourceRepos:
    - https://github.com/Falo04/homelab.git
    - https://argoproj.github.io/argo-helm
    - https://helm.releases.hashicorp.com
    - https://traefik.github.io/charts
    - oci://quay.io/jetstack/charts/cert-manager
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
