apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: service-apps-project
  namespace: argocd
spec:
  description: "All third party apps"
  sourceRepos:
    - https://github.com/Falo04/homelab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: wallos
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
