apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-backup-values
data:
  clusterName: authentik-postgres
  destinationPath: s3://authentik-bucket/
  vaultMount: k3s-infra
  vaultPath: authentik/backup
