apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - vault-auth.yaml
  - secret-key.yaml
  - postgres.yaml
  - authentik-cert.yaml
  - authentik-ingress.yaml
  - backup-values.yaml

components:
  - ../../../base/cnpg-backup
