# Authentik needs a `AUTHENTIK_SECRET_KEY`, which sould be staying in this path
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-secret-key-secret
  namespace: authentik
spec:
  vaultAuthRef: vault-k8s
  mount: k3s-infra
  type: kv-v2
  path: authentik/secret-key
  refreshAfter: 1h
  destination:
    create: true
    name: secret-key-secret
