apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - vault-auth.yaml
  - auth-secret.yaml
  - postgres.yaml
  - deployment.yaml
  - servicemonitor.yaml
  - ntfy-cert.yaml
  - ntfy-ingress.yaml

configMapGenerator:
  - name: ntfy-config
    namespace: ntfy
    files:
      - server.yml
