apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ntfy-postgres-test
  namespace: ntfy
spec:
  instances: 1
  storage:
    size: 2Gi
  bootstrap:
    recovery:
      source: garage
  externalClusters:
    - name: garage
      plugin: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: garage-store
        serverName: ntfy-postgres
