apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fronius-exporter
  namespace: solar
  labels:
    app.kubernetes.io/name: fronius-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fronius-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 15s
